---

    - name: install base packages
      apt: pkg=nginx state=latest
      sudo: yes

    - name: Remove the default app
      command: rm -rf /etc/nginx/sites-enabled/default
      sudo: yes

    - name: Remove the app's config, if exists
      command: rm -rf /etc/nginx/sites-enabled/default
      sudo: yes

    - name: Remove the app's symlink, if exists
      command: rm -rf /etc/nginx/sites-enabled/{{app_name}}
      sudo: yes

    - name: Configure nginx for the app
      template: src=../templates/nginx/sites-available.conf.j2 dest=/etc/nginx/sites-available/{{app_name}} group=www-data owner=www-data force=yes
      sudo: yes

    - name: Enable the app
      command: ln -s /etc/nginx/sites-available/{{app_name}} /etc/nginx/sites-enabled/{{app_name}}
      sudo: yes

    - name: Restart nginx
      service: name=nginx state=restarted
      sudo: yes